name: 'Setup Buildtools'
description: 'Setup a Buildtools and add it to the PATH'
author: 'Buildtools'
inputs:
  buildtools-version:
    description: 'The version to download (if necessary) and use. Supports semver spec and ranges.'
    default: 'latest'
  debug-log:
    description: 'Enabled more verbose logging.'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: install_buildtools.sh ${{ inputs.buildtools-version }} ${{ inputs.debug-log }}
      shell: bash
      if: runner.os == 'Linux'
#    - run: ./install_buildtools.sh
#      if: runner.os == 'Windows'
#      shell: bash
branding:
  icon: 'package'
  color: 'green'
